**Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.**

In [4]:
import numpy as np
inp = np.array([1,2,3,4,5,6])
N = 6
mat = np.array([inp**(N-i-1) for i in range(N)])
print(mat.T)

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]


In [6]:
#using vander function

inp = np.array([1,2,3,4,5])
matv = np.vander(inp,increasing=True)
print(matv)

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


**Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below**

i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

**Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Write a function to find moving average in an array over a window:
Test it over[3,5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.**

In [30]:
k=3
N=13
y =[]
x = np.array([3,5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
def movavg(x,N,k):
    for i in range(N-k+1):
        avg=0
        avg=sum(x[i:i+k])/k
        y.append(avg)
    return y

print(" Moving average is: ", np.array(movavg(x,N,k)).round(2))
print("Lenght of moving sequence: ",N-k+1)
        

 Moving average is:  [  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
Lenght of moving sequence:  11


In [35]:
# with cumsum function
# This does sum as [a1,a1+a2,a1+a2+a3......]
# so the list from the kth element we try to subtract list in reverse order till kth element
# then we print the average from kth element
def moving_avg(x,k):
    csum = np.cumsum(x,dtype=float)
    print(csum)
    print(csum[k:])
    print(csum[:-k])
    csum[k:] = csum[k:]-csum[:-k]
    print(csum)
    return csum[k-1:]/k

print(" Moving average is: ", np.array(moving_avg(x,k)).round(2))
print("Lenght of moving sequence: ",N-k+1)


[  3.   8.  15.  17.  25.  35.  46. 111. 183. 264. 363. 463. 613.]
[ 17.  25.  35.  46. 111. 183. 264. 363. 463. 613.]
[  3.   8.  15.  17.  25.  35.  46. 111. 183. 264.]
[  3.   8.  15.  14.  17.  20.  29.  86. 148. 218. 252. 280. 349.]
 Moving average is:  [  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
Lenght of moving sequence:  11
